export const tradeHistory = [
  {
    id: 1,
    date: '2024-07-01',
    time: '09:30',
    instrument: 'Nifty 50',
    type: 'Buy',
    quantity: 50,
    price: 22000,
    pnl: 2500,
    tradeType: 'Intraday',
    direction: 'Buy',
    exitPrice: 22050.5,
    stopLoss: 21950.0,
    target: 22100.0,
    exitReason: 'Target Hit',
    grossPnl: 2500,
    netPnl: 2450,
    charges: 50,
    strategyUsed: 'Breakout',
    setupName: 'Flag Pattern',
    confirmationIndicators: 'RSI, MACD',
    confidenceLevel: 8,
    emotionsBefore: 'Calm',
    emotionsAfter: 'Satisfied',
    tradeNotes:
      'Good entry, followed plan. This is a longer note to test the popup functionality and ensure it displays all the text properly without truncation. It should wrap and then truncate after two lines.',
    mistakes:
      'None, this was a perfectly executed trade with no mistakes whatsoever.',
    whatDidWell:
      'Stuck to the strategy. Maintained discipline throughout the trade duration and managed risk effectively.',
    tags: 'Perfect Setup',
  },
  {
    id: 2,
    date: '2024-07-02',
    time: '10:15',
    instrument: 'Bank Nifty',
    type: 'Sell',
    quantity: 25,
    price: 47500,
    pnl: -1200,
    tradeType: 'Intraday',
    direction: 'Sell',
    exitPrice: 47600.0,
    stopLoss: 47400.0,
    target: 47300.0,
    exitReason: 'SL Hit',
    grossPnl: -1200,
    netPnl: -1250,
    charges: 50,
    strategyUsed: 'Reversal',
    setupName: '',
    confirmationIndicators: 'VWAP',
    confidenceLevel: 6,
    emotionsBefore: 'Overconfident',
    emotionsAfter: 'Frustrated',
    tradeNotes:
      'Missed SL by a few points. The volatility was higher than expected, leading to a quick stop-loss hit. Should have waited for more confirmation.',
    mistakes:
      "Didn't adjust SL quickly enough. Also, entered without strong confirmation and ignored early warning signs.",
    whatDidWell: 'Exited when SL hit. Did not average down or chase the trade.',
    tags: 'Missed SL',
  },
  {
    id: 3,
    date: '2024-07-03',
    time: '14:00',
    instrument: 'Nifty 50',
    type: 'Sell',
    quantity: 75,
    price: 22100,
    pnl: 3000,
    tradeType: 'Swing',
    direction: 'Sell',
    exitPrice: 22060.0,
    stopLoss: 22150.0,
    target: 22000.0,
    exitReason: 'Manual Exit',
    grossPnl: 3000,
    netPnl: 2900,
    charges: 100,
    strategyUsed: 'Trendline',
    setupName: 'Descending Triangle',
    confirmationIndicators: 'Volume',
    confidenceLevel: 7,
    emotionsBefore: 'Calm',
    emotionsAfter: 'Happy',
    tradeNotes:
      'Booked profit early due to market volatility. Saw some weakness at resistance and decided to close the position before it reversed completely.',
    mistakes:
      'Could have held longer for the full target, but better safe than sorry. Missed out on a bit more profit.',
    whatDidWell:
      'Protected profits. Identified the resistance level accurately and acted decisively.',
    tags: 'Trendline',
  },
  {
    id: 4,
    date: '2024-07-04',
    time: '09:45',
    instrument: 'Bank Nifty',
    type: 'Buy',
    quantity: 30,
    price: 47000,
    pnl: 1800,
    tradeType: 'Positional',
    direction: 'Buy',
    exitPrice: 47060.0,
    stopLoss: 46900.0,
    target: 47200.0,
    exitReason: 'Target Hit',
    grossPnl: 1800,
    netPnl: 1750,
    charges: 50,
    strategyUsed: 'Support',
    setupName: 'Double Bottom',
    confirmationIndicators: 'RSI',
    confidenceLevel: 9,
    emotionsBefore: 'Calm',
    emotionsAfter: 'Satisfied',
    tradeNotes:
      'Long term trade, worked out well. The support held perfectly as anticipated, confirming the bullish outlook.',
    mistakes:
      'None, this trade was executed perfectly according to plan and analysis.',
    whatDidWell:
      'Patience paid off. Trusted the analysis and held through minor fluctuations, allowing the trade to reach its target.',
    tags: 'Perfect Setup',
  },
  {
    id: 5,
    date: '2024-07-05',
    time: '11:20',
    instrument: 'Ethereum',
    type: 'Buy',
    quantity: 2,
    price: 3500,
    pnl: 500,
    tradeType: 'Swing',
    direction: 'Buy',
    exitPrice: 3750.0,
    stopLoss: 3400.0,
    target: 3800.0,
    exitReason: 'Manual Exit',
    grossPnl: 500,
    netPnl: 480,
    charges: 20,
    strategyUsed: 'Self Setup',
    setupName: 'Crypto Breakout',
    confirmationIndicators: 'MACD',
    confidenceLevel: 7,
    emotionsBefore: 'Excited',
    emotionsAfter: 'Satisfied',
    tradeNotes:
      'First crypto trade, good learning. The breakout was clean, but I was a bit nervous initially due to unfamiliarity with the asset class.',
    mistakes:
      'Over-leveraged slightly. Should have started with a smaller position size to manage initial risk better.',
    whatDidWell:
      'Researched well before entry. Managed to exit profitably despite initial jitters and learned from the experience.',
    tags: 'Crypto',
  },
  {
    id: 6,
    date: '2024-07-06',
    time: '13:00',
    instrument: 'Bitcoin',
    type: 'Sell',
    quantity: 0.5,
    price: 60000,
    pnl: -1000,
    tradeType: 'Scalping',
    direction: 'Sell',
    exitPrice: 60500.0,
    stopLoss: 59800.0,
    target: 59500.0,
    exitReason: 'SL Hit',
    grossPnl: -1000,
    netPnl: -1010,
    charges: 10,
    strategyUsed: 'Resistance',
    setupName: '',
    confirmationIndicators: 'Bollinger Bands',
    confidenceLevel: 5,
    emotionsBefore: 'Anxious',
    emotionsAfter: 'Frustrated',
    tradeNotes:
      'Market moved against quickly. The resistance was stronger than expected, leading to a rapid decline. Should have waited for more confirmation.',
    mistakes:
      'Entered too late. Did not confirm with other indicators and acted impulsively.',
    whatDidWell:
      'Cut losses quickly. Did not let emotions take over after the loss, which prevented further damage.',
    tags: 'Crypto, SL Hit',
  },
  {
    id: 7,
    date: '2024-07-07',
    time: '09:00',
    instrument: 'Nifty 50',
    type: 'Buy',
    quantity: 100,
    price: 22200,
    pnl: 4000,
    tradeType: 'Intraday',
    direction: 'Buy',
    exitPrice: 22240.0,
    stopLoss: 22180.0,
    target: 22250.0,
    exitReason: 'Target Hit',
    grossPnl: 4000,
    netPnl: 3900,
    charges: 100,
    strategyUsed: 'Price Action',
    setupName: 'Morning Star',
    confirmationIndicators: 'Volume',
    confidenceLevel: 9,
    emotionsBefore: 'Calm',
    emotionsAfter: 'Happy',
    tradeNotes:
      'Perfect setup, executed flawlessly. The price action confirmed the bullish reversal, and volume supported the move.',
    mistakes:
      'None, this was a textbook trade executed with precision and discipline.',
    whatDidWell:
      'Disciplined entry and exit. Waited for the ideal setup and did not deviate from the plan.',
    tags: 'Perfect Setup',
  },
  {
    id: 8,
    date: '2024-07-08',
    time: '10:30',
    instrument: 'Reliance',
    type: 'Buy',
    quantity: 20,
    price: 2900,
    pnl: 300,
    tradeType: 'Swing',
    direction: 'Buy',
    exitPrice: 2915.0,
    stopLoss: 2880.0,
    target: 2930.0,
    exitReason: 'Manual Exit',
    grossPnl: 300,
    netPnl: 280,
    charges: 20,
    strategyUsed: 'Support',
    setupName: '',
    confirmationIndicators: 'RSI',
    confidenceLevel: 7,
    emotionsBefore: 'Neutral',
    emotionsAfter: 'Satisfied',
    tradeNotes:
      'Small profit, but good execution. The stock bounced off the support level as expected, showing resilience.',
    mistakes:
      'Could have waited for full target, but decided to de-risk due to broader market uncertainty.',
    whatDidWell:
      'Managed risk well. Identified a strong support zone and took a calculated entry.',
    tags: 'Equity',
  },
  {
    id: 9,
    date: '2024-07-09',
    time: '15:10',
    instrument: 'Bank Nifty',
    type: 'Sell',
    quantity: 50,
    price: 47800,
    pnl: -2000,
    tradeType: 'Intraday',
    direction: 'Sell',
    exitPrice: 47900.0,
    stopLoss: 47750.0,
    target: 47600.0,
    exitReason: 'SL Hit',
    grossPnl: -2000,
    netPnl: -2050,
    charges: 50,
    strategyUsed: 'Trendline',
    setupName: '',
    confirmationIndicators: 'MACD',
    confidenceLevel: 4,
    emotionsBefore: 'Fearful',
    emotionsAfter: 'Regretful',
    tradeNotes:
      'Market reversed unexpectedly. The trendline break was a false signal, and the momentum quickly shifted.',
    mistakes:
      'Ignored divergence. Did not wait for retest confirmation after the initial break.',
    whatDidWell:
      'Stuck to SL. Did not let the loss escalate by adhering to the stop-loss order.',
    tags: 'SL Hit',
  },
  {
    id: 10,
    date: '2024-07-10',
    time: '11:00',
    instrument: 'Gold Futures',
    type: 'Buy',
    quantity: 1,
    price: 72000,
    pnl: 1500,
    tradeType: 'Positional',
    direction: 'Buy',
    exitPrice: 72150.0,
    stopLoss: 71800.0,
    target: 72300.0,
    exitReason: 'Target Hit',
    grossPnl: 1500,
    netPnl: 1400,
    charges: 100,
    strategyUsed: 'Moving Average',
    setupName: '',
    confirmationIndicators: 'Volume',
    confidenceLevel: 8,
    emotionsBefore: 'Calm',
    emotionsAfter: 'Satisfied',
    tradeNotes:
      'Long term view paid off. The moving average crossover provided a strong entry signal, and the trend continued as expected.',
    mistakes:
      'None, this was a well-researched and patiently executed positional trade.',
    whatDidWell:
      'Patient holding. Followed the long-term trend and did not get shaken out by minor corrections.',
    tags: 'Commodity',
  },
  {
    id: 11,
    date: '2024-07-11',
    time: '10:00',
    instrument: 'Silver Futures',
    type: 'Sell',
    quantity: 5,
    price: 90000,
    pnl: -500,
    tradeType: 'Intraday',
    direction: 'Sell',
    exitPrice: 90100.0,
    stopLoss: 89950.0,
    target: 89800.0,
    exitReason: 'Manual Exit',
    grossPnl: -500,
    netPnl: -520,
    charges: 20,
    strategyUsed: 'Resistance',
    setupName: '',
    confirmationIndicators: 'RSI, Stochastic',
    confidenceLevel: 6,
    emotionsBefore: 'Neutral',
    emotionsAfter: 'Frustrated',
    tradeNotes:
      'Market choppy, exited early to avoid larger loss. The resistance was not clearly holding.',
    mistakes:
      'Entered in a choppy market. Did not wait for clear trend confirmation.',
    whatDidWell: 'Recognized choppy market and exited with small loss.',
    tags: 'Commodity, Choppy',
  },
  {
    id: 12,
    date: '2024-07-12',
    time: '14:30',
    instrument: 'USDINR',
    type: 'Buy',
    quantity: 1000,
    price: 83.5,
    pnl: 1000,
    tradeType: 'Intraday',
    direction: 'Buy',
    exitPrice: 83.6,
    stopLoss: 83.45,
    target: 83.65,
    exitReason: 'Target Hit',
    grossPnl: 1000,
    netPnl: 980,
    charges: 20,
    strategyUsed: 'Support',
    setupName: '',
    confirmationIndicators: 'VWAP',
    confidenceLevel: 7,
    emotionsBefore: 'Calm',
    emotionsAfter: 'Satisfied',
    tradeNotes:
      'Good bounce from support. The currency pair respected the identified support level.',
    mistakes: 'None.',
    whatDidWell: 'Quick entry and exit. Identified a strong support zone.',
    tags: 'Currency',
  },
]
